### PR TITLE
merge modified

### PR DESCRIPTION
**Pull request by reyesvicente**
img added

### CODE REVIEW

**Comment by EthanZeigler** [comment]
You know you've been submitting pull requests to the master, right? This is a template and it seems you're submitting your own implementation as a pull request.

**Comment by EthanZeigler** [comment]
Github (git) can be a little hard to understand, believe me. Lol. Github’s management makes it even worse at times.

**Comment by reyesvicente** [comment]
What do you mean by the management makes it even worse?

Best Regards,
Vicente G. Reyes

**Comment by EthanZeigler** [comment]
GitHub has a lot of its own qwirks that can be difficult to understand.

btw, to fix your issue, run these commands.

git remote remove origin (it's probably origin)

then make a new GitHub repo for your thing, and copy the repository link it provides you to use. it will end in .git

then run git remote add origin <that url>
then you can commit and push as you'd like without any worries.

**Comment by EthanZeigler** [comment]
wait, my GitHub app glitched. 

git remote add origin [url]

**Comment by reyesvicente** [comment]
Alright. I’ll send a message if I’m having a troubles but I should pull it off easy.

Best Regards,
Vicente G. Reyes

**Pull request closed without merging**
